DINOSAURS = [
  {
    "name": "Tyrannosaurus Rex",
    "emoji": "\ud83e\udd96",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 40,
    "attack": 10,
    "defense": 8,
    "speed": 10,
    "level": 1,
    "fun": "Tyrannosaurus Rex stomps wildly in the ancient world!"
  },
  {
    "name": "Spinosaurus",
    "emoji": "\ud83e\udd95",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 41,
    "attack": 11,
    "defense": 9,
    "speed": 11,
    "level": 1,
    "fun": "Spinosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Giganotosaurus",
    "emoji": "\ud83e\udd85",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 42,
    "attack": 12,
    "defense": 10,
    "speed": 12,
    "level": 1,
    "fun": "Giganotosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Carnotaurus",
    "emoji": "\ud83e\udda3",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 43,
    "attack": 13,
    "defense": 11,
    "speed": 13,
    "level": 1,
    "fun": "Carnotaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Indominus Rex",
    "emoji": "\ud83d\udd25",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 44,
    "attack": 14,
    "defense": 12,
    "speed": 14,
    "level": 1,
    "fun": "Indominus Rex stomps wildly in the ancient world!"
  },
  {
    "name": "Mosasaurus",
    "emoji": "\ud83d\udc80",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 45,
    "attack": 15,
    "defense": 13,
    "speed": 15,
    "level": 1,
    "fun": "Mosasaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Quetzalcoatlus",
    "emoji": "\ud83c\udf0a",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 46,
    "attack": 16,
    "defense": 14,
    "speed": 16,
    "level": 1,
    "fun": "Quetzalcoatlus stomps wildly in the ancient world!"
  },
  {
    "name": "Megalodon",
    "emoji": "\ud83e\udd6c",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 47,
    "attack": 17,
    "defense": 15,
    "speed": 17,
    "level": 1,
    "fun": "Megalodon stomps wildly in the ancient world!"
  },
  {
    "name": "Saber-tooth Tiger",
    "emoji": "\ud83c\udfba",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 48,
    "attack": 18,
    "defense": 16,
    "speed": 18,
    "level": 1,
    "fun": "Saber-tooth Tiger stomps wildly in the ancient world!"
  },
  {
    "name": "Woolly Mammoth",
    "emoji": "\ud83d\udc51",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 49,
    "attack": 19,
    "defense": 17,
    "speed": 19,
    "level": 1,
    "fun": "Woolly Mammoth stomps wildly in the ancient world!"
  },
  {
    "name": "Velociraptor",
    "emoji": "\ud83c\udfc3\u200d\u2642\ufe0f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 50,
    "attack": 20,
    "defense": 18,
    "speed": 20,
    "level": 1,
    "fun": "Velociraptor stomps wildly in the ancient world!"
  },
  {
    "name": "Allosaurus",
    "emoji": "\ud83d\udc0d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 51,
    "attack": 21,
    "defense": 19,
    "speed": 21,
    "level": 1,
    "fun": "Allosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Ankylosaurus",
    "emoji": "\ud83d\udc2d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 52,
    "attack": 22,
    "defense": 20,
    "speed": 22,
    "level": 1,
    "fun": "Ankylosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Dilophosaurus",
    "emoji": "\ud83e\udeb6",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 53,
    "attack": 23,
    "defense": 21,
    "speed": 23,
    "level": 1,
    "fun": "Dilophosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Therizinosaurus",
    "emoji": "\ud83c\udfad",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 54,
    "attack": 24,
    "defense": 22,
    "speed": 24,
    "level": 1,
    "fun": "Therizinosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Utahraptor",
    "emoji": "\ud83c\udf3f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 55,
    "attack": 25,
    "defense": 8,
    "speed": 25,
    "level": 1,
    "fun": "Utahraptor stomps wildly in the ancient world!"
  },
  {
    "name": "Ceratosaurus",
    "emoji": "\ud83d\udc26",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 56,
    "attack": 26,
    "defense": 9,
    "speed": 26,
    "level": 1,
    "fun": "Ceratosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Baryonyx",
    "emoji": "\ud83e\udd96",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 57,
    "attack": 27,
    "defense": 10,
    "speed": 27,
    "level": 1,
    "fun": "Baryonyx stomps wildly in the ancient world!"
  },
  {
    "name": "Deinonychus",
    "emoji": "\ud83e\udd95",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 58,
    "attack": 28,
    "defense": 11,
    "speed": 28,
    "level": 1,
    "fun": "Deinonychus stomps wildly in the ancient world!"
  },
  {
    "name": "Carcharodontosaurus",
    "emoji": "\ud83e\udd85",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 59,
    "attack": 29,
    "defense": 12,
    "speed": 29,
    "level": 1,
    "fun": "Carcharodontosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Concavenator",
    "emoji": "\ud83e\udda3",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 60,
    "attack": 10,
    "defense": 13,
    "speed": 10,
    "level": 1,
    "fun": "Concavenator stomps wildly in the ancient world!"
  },
  {
    "name": "Acrocanthosaurus",
    "emoji": "\ud83d\udd25",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 61,
    "attack": 11,
    "defense": 14,
    "speed": 11,
    "level": 1,
    "fun": "Acrocanthosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Albertosaurus",
    "emoji": "\ud83d\udc80",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 62,
    "attack": 12,
    "defense": 15,
    "speed": 12,
    "level": 1,
    "fun": "Albertosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Pteranodon",
    "emoji": "\ud83c\udf0a",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 63,
    "attack": 13,
    "defense": 16,
    "speed": 13,
    "level": 1,
    "fun": "Pteranodon stomps wildly in the ancient world!"
  },
  {
    "name": "Plesiosaurus",
    "emoji": "\ud83e\udd6c",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 64,
    "attack": 14,
    "defense": 17,
    "speed": 14,
    "level": 1,
    "fun": "Plesiosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Kentrosaurus",
    "emoji": "\ud83c\udfba",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 65,
    "attack": 15,
    "defense": 18,
    "speed": 15,
    "level": 1,
    "fun": "Kentrosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Amargasaurus",
    "emoji": "\ud83d\udc51",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 66,
    "attack": 16,
    "defense": 19,
    "speed": 16,
    "level": 1,
    "fun": "Amargasaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Microraptor",
    "emoji": "\ud83c\udfc3\u200d\u2642\ufe0f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 67,
    "attack": 17,
    "defense": 20,
    "speed": 17,
    "level": 1,
    "fun": "Microraptor stomps wildly in the ancient world!"
  },
  {
    "name": "Archaeopteryx",
    "emoji": "\ud83d\udc0d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 68,
    "attack": 18,
    "defense": 21,
    "speed": 18,
    "level": 1,
    "fun": "Archaeopteryx stomps wildly in the ancient world!"
  },
  {
    "name": "Giant Ground Sloth",
    "emoji": "\ud83d\udc2d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 69,
    "attack": 19,
    "defense": 22,
    "speed": 19,
    "level": 1,
    "fun": "Giant Ground Sloth stomps wildly in the ancient world!"
  },
  {
    "name": "Argentavis",
    "emoji": "\ud83e\udeb6",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 40,
    "attack": 20,
    "defense": 8,
    "speed": 20,
    "level": 1,
    "fun": "Argentavis stomps wildly in the ancient world!"
  },
  {
    "name": "Leedsichthys",
    "emoji": "\ud83c\udfad",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 41,
    "attack": 21,
    "defense": 9,
    "speed": 21,
    "level": 1,
    "fun": "Leedsichthys stomps wildly in the ancient world!"
  },
  {
    "name": "Dunkleosteus",
    "emoji": "\ud83c\udf3f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 42,
    "attack": 22,
    "defense": 10,
    "speed": 22,
    "level": 1,
    "fun": "Dunkleosteus stomps wildly in the ancient world!"
  },
  {
    "name": "Kronosaurus",
    "emoji": "\ud83d\udc26",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 43,
    "attack": 23,
    "defense": 11,
    "speed": 23,
    "level": 1,
    "fun": "Kronosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Tarbosaurus",
    "emoji": "\ud83e\udd96",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 44,
    "attack": 24,
    "defense": 12,
    "speed": 24,
    "level": 1,
    "fun": "Tarbosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Majungasaurus",
    "emoji": "\ud83e\udd95",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 45,
    "attack": 25,
    "defense": 13,
    "speed": 25,
    "level": 1,
    "fun": "Majungasaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Irritator",
    "emoji": "\ud83e\udd85",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 46,
    "attack": 26,
    "defense": 14,
    "speed": 26,
    "level": 1,
    "fun": "Irritator stomps wildly in the ancient world!"
  },
  {
    "name": "Mapusaurus",
    "emoji": "\ud83e\udda3",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 47,
    "attack": 27,
    "defense": 15,
    "speed": 27,
    "level": 1,
    "fun": "Mapusaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Saurophaganax",
    "emoji": "\ud83d\udd25",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 48,
    "attack": 28,
    "defense": 16,
    "speed": 28,
    "level": 1,
    "fun": "Saurophaganax stomps wildly in the ancient world!"
  },
  {
    "name": "Yangchuanosaurus",
    "emoji": "\ud83d\udc80",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 49,
    "attack": 29,
    "defense": 17,
    "speed": 29,
    "level": 1,
    "fun": "Yangchuanosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Cave Bear",
    "emoji": "\ud83c\udf0a",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 50,
    "attack": 10,
    "defense": 18,
    "speed": 10,
    "level": 1,
    "fun": "Cave Bear stomps wildly in the ancient world!"
  },
  {
    "name": "Triceratops",
    "emoji": "\ud83e\udd6c",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 51,
    "attack": 11,
    "defense": 19,
    "speed": 11,
    "level": 1,
    "fun": "Triceratops stomps wildly in the ancient world!"
  },
  {
    "name": "Stegosaurus",
    "emoji": "\ud83c\udfba",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 52,
    "attack": 12,
    "defense": 20,
    "speed": 12,
    "level": 1,
    "fun": "Stegosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Brachiosaurus",
    "emoji": "\ud83d\udc51",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 53,
    "attack": 13,
    "defense": 21,
    "speed": 13,
    "level": 1,
    "fun": "Brachiosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Parasaurolophus",
    "emoji": "\ud83c\udfc3\u200d\u2642\ufe0f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 54,
    "attack": 14,
    "defense": 22,
    "speed": 14,
    "level": 1,
    "fun": "Parasaurolophus stomps wildly in the ancient world!"
  },
  {
    "name": "Diplodocus",
    "emoji": "\ud83d\udc0d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 55,
    "attack": 15,
    "defense": 8,
    "speed": 15,
    "level": 1,
    "fun": "Diplodocus stomps wildly in the ancient world!"
  },
  {
    "name": "Iguanodon",
    "emoji": "\ud83d\udc2d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 56,
    "attack": 16,
    "defense": 9,
    "speed": 16,
    "level": 1,
    "fun": "Iguanodon stomps wildly in the ancient world!"
  },
  {
    "name": "Gallimimus",
    "emoji": "\ud83e\udeb6",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 57,
    "attack": 17,
    "defense": 10,
    "speed": 17,
    "level": 1,
    "fun": "Gallimimus stomps wildly in the ancient world!"
  },
  {
    "name": "Compsognathus",
    "emoji": "\ud83c\udfad",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 58,
    "attack": 18,
    "defense": 11,
    "speed": 18,
    "level": 1,
    "fun": "Compsognathus stomps wildly in the ancient world!"
  },
  {
    "name": "Hadrosaurus",
    "emoji": "\ud83c\udf3f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 59,
    "attack": 19,
    "defense": 12,
    "speed": 19,
    "level": 1,
    "fun": "Hadrosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Edmontosaurus",
    "emoji": "\ud83d\udc26",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 60,
    "attack": 20,
    "defense": 13,
    "speed": 20,
    "level": 1,
    "fun": "Edmontosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Maiasaura",
    "emoji": "\ud83e\udd96",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 61,
    "attack": 21,
    "defense": 14,
    "speed": 21,
    "level": 1,
    "fun": "Maiasaura stomps wildly in the ancient world!"
  },
  {
    "name": "Ouranosaurus",
    "emoji": "\ud83e\udd95",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 62,
    "attack": 22,
    "defense": 15,
    "speed": 22,
    "level": 1,
    "fun": "Ouranosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Protoceratops",
    "emoji": "\ud83e\udd85",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 63,
    "attack": 23,
    "defense": 16,
    "speed": 23,
    "level": 1,
    "fun": "Protoceratops stomps wildly in the ancient world!"
  },
  {
    "name": "Hypsilophodon",
    "emoji": "\ud83e\udda3",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 64,
    "attack": 24,
    "defense": 17,
    "speed": 24,
    "level": 1,
    "fun": "Hypsilophodon stomps wildly in the ancient world!"
  },
  {
    "name": "Dryosaurus",
    "emoji": "\ud83d\udd25",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 65,
    "attack": 25,
    "defense": 18,
    "speed": 25,
    "level": 1,
    "fun": "Dryosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Corythosaurus",
    "emoji": "\ud83d\udc80",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 66,
    "attack": 26,
    "defense": 19,
    "speed": 26,
    "level": 1,
    "fun": "Corythosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Lambeosaurus",
    "emoji": "\ud83c\udf0a",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 67,
    "attack": 27,
    "defense": 20,
    "speed": 27,
    "level": 1,
    "fun": "Lambeosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Styracosaurus",
    "emoji": "\ud83e\udd6c",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 68,
    "attack": 28,
    "defense": 21,
    "speed": 28,
    "level": 1,
    "fun": "Styracosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Centrosaurus",
    "emoji": "\ud83c\udfba",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 69,
    "attack": 29,
    "defense": 22,
    "speed": 29,
    "level": 1,
    "fun": "Centrosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Chasmosaurus",
    "emoji": "\ud83d\udc51",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 40,
    "attack": 10,
    "defense": 8,
    "speed": 10,
    "level": 1,
    "fun": "Chasmosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Apatosaurus",
    "emoji": "\ud83c\udfc3\u200d\u2642\ufe0f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 41,
    "attack": 11,
    "defense": 9,
    "speed": 11,
    "level": 1,
    "fun": "Apatosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Camarasaurus",
    "emoji": "\ud83d\udc0d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 42,
    "attack": 12,
    "defense": 10,
    "speed": 12,
    "level": 1,
    "fun": "Camarasaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Saltasaurus",
    "emoji": "\ud83d\udc2d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 43,
    "attack": 13,
    "defense": 11,
    "speed": 13,
    "level": 1,
    "fun": "Saltasaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Ornithomimus",
    "emoji": "\ud83e\udeb6",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 44,
    "attack": 14,
    "defense": 12,
    "speed": 14,
    "level": 1,
    "fun": "Ornithomimus stomps wildly in the ancient world!"
  },
  {
    "name": "Struthiomimus",
    "emoji": "\ud83c\udfad",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 45,
    "attack": 15,
    "defense": 13,
    "speed": 15,
    "level": 1,
    "fun": "Struthiomimus stomps wildly in the ancient world!"
  },
  {
    "name": "Dracorex",
    "emoji": "\ud83c\udf3f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 46,
    "attack": 16,
    "defense": 14,
    "speed": 16,
    "level": 1,
    "fun": "Dracorex stomps wildly in the ancient world!"
  },
  {
    "name": "Stygimoloch",
    "emoji": "\ud83d\udc26",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 47,
    "attack": 17,
    "defense": 15,
    "speed": 17,
    "level": 1,
    "fun": "Stygimoloch stomps wildly in the ancient world!"
  },
  {
    "name": "Pachycephalosaurus",
    "emoji": "\ud83e\udd96",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 48,
    "attack": 18,
    "defense": 16,
    "speed": 18,
    "level": 1,
    "fun": "Pachycephalosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Orodromeus",
    "emoji": "\ud83e\udd95",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 49,
    "attack": 19,
    "defense": 17,
    "speed": 19,
    "level": 1,
    "fun": "Orodromeus stomps wildly in the ancient world!"
  },
  {
    "name": "Lesothosaurus",
    "emoji": "\ud83e\udd85",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 50,
    "attack": 20,
    "defense": 18,
    "speed": 20,
    "level": 1,
    "fun": "Lesothosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Heterodontosaurus",
    "emoji": "\ud83e\udda3",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 51,
    "attack": 21,
    "defense": 19,
    "speed": 21,
    "level": 1,
    "fun": "Heterodontosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Scutellosaurus",
    "emoji": "\ud83d\udd25",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 52,
    "attack": 22,
    "defense": 20,
    "speed": 22,
    "level": 1,
    "fun": "Scutellosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Scelidosaurus",
    "emoji": "\ud83d\udc80",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 53,
    "attack": 23,
    "defense": 21,
    "speed": 23,
    "level": 1,
    "fun": "Scelidosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Plateosaurus",
    "emoji": "\ud83c\udf0a",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 54,
    "attack": 24,
    "defense": 22,
    "speed": 24,
    "level": 1,
    "fun": "Plateosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Massospondylus",
    "emoji": "\ud83e\udd6c",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 55,
    "attack": 25,
    "defense": 8,
    "speed": 25,
    "level": 1,
    "fun": "Massospondylus stomps wildly in the ancient world!"
  },
  {
    "name": "Riojasaurus",
    "emoji": "\ud83c\udfba",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 56,
    "attack": 26,
    "defense": 9,
    "speed": 26,
    "level": 1,
    "fun": "Riojasaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Anchisaurus",
    "emoji": "\ud83d\udc51",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 57,
    "attack": 27,
    "defense": 10,
    "speed": 27,
    "level": 1,
    "fun": "Anchisaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Coelophysis",
    "emoji": "\ud83c\udfc3\u200d\u2642\ufe0f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 58,
    "attack": 28,
    "defense": 11,
    "speed": 28,
    "level": 1,
    "fun": "Coelophysis stomps wildly in the ancient world!"
  },
  {
    "name": "Herrerasaurus",
    "emoji": "\ud83d\udc0d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 59,
    "attack": 29,
    "defense": 12,
    "speed": 29,
    "level": 1,
    "fun": "Herrerasaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Eoraptor",
    "emoji": "\ud83d\udc2d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 60,
    "attack": 10,
    "defense": 13,
    "speed": 10,
    "level": 1,
    "fun": "Eoraptor stomps wildly in the ancient world!"
  },
  {
    "name": "Staurikosaurus",
    "emoji": "\ud83e\udeb6",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 61,
    "attack": 11,
    "defense": 14,
    "speed": 11,
    "level": 1,
    "fun": "Staurikosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Elasmosaurus",
    "emoji": "\ud83c\udfad",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 62,
    "attack": 12,
    "defense": 15,
    "speed": 12,
    "level": 1,
    "fun": "Elasmosaurus stomps wildly in the ancient world!"
  },
  {
    "name": "Rhamphorhynchus",
    "emoji": "\ud83c\udf3f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 63,
    "attack": 13,
    "defense": 16,
    "speed": 13,
    "level": 1,
    "fun": "Rhamphorhynchus stomps wildly in the ancient world!"
  },
  {
    "name": "Dire Wolf",
    "emoji": "\ud83d\udc26",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 64,
    "attack": 14,
    "defense": 17,
    "speed": 14,
    "level": 1,
    "fun": "Dire Wolf stomps wildly in the ancient world!"
  },
  {
    "name": "Irish Elk",
    "emoji": "\ud83e\udd96",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 65,
    "attack": 15,
    "defense": 18,
    "speed": 15,
    "level": 1,
    "fun": "Irish Elk stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_87",
    "emoji": "\ud83e\udd95",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 66,
    "attack": 16,
    "defense": 19,
    "speed": 16,
    "level": 1,
    "fun": "Dino_87 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_88",
    "emoji": "\ud83e\udd85",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 67,
    "attack": 17,
    "defense": 20,
    "speed": 17,
    "level": 1,
    "fun": "Dino_88 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_89",
    "emoji": "\ud83e\udda3",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 68,
    "attack": 18,
    "defense": 21,
    "speed": 18,
    "level": 1,
    "fun": "Dino_89 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_90",
    "emoji": "\ud83d\udd25",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 69,
    "attack": 19,
    "defense": 22,
    "speed": 19,
    "level": 1,
    "fun": "Dino_90 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_91",
    "emoji": "\ud83d\udc80",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 40,
    "attack": 20,
    "defense": 8,
    "speed": 20,
    "level": 1,
    "fun": "Dino_91 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_92",
    "emoji": "\ud83c\udf0a",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 41,
    "attack": 21,
    "defense": 9,
    "speed": 21,
    "level": 1,
    "fun": "Dino_92 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_93",
    "emoji": "\ud83e\udd6c",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 42,
    "attack": 22,
    "defense": 10,
    "speed": 22,
    "level": 1,
    "fun": "Dino_93 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_94",
    "emoji": "\ud83c\udfba",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 43,
    "attack": 23,
    "defense": 11,
    "speed": 23,
    "level": 1,
    "fun": "Dino_94 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_95",
    "emoji": "\ud83d\udc51",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 44,
    "attack": 24,
    "defense": 12,
    "speed": 24,
    "level": 1,
    "fun": "Dino_95 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_96",
    "emoji": "\ud83c\udfc3\u200d\u2642\ufe0f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 45,
    "attack": 25,
    "defense": 13,
    "speed": 25,
    "level": 1,
    "fun": "Dino_96 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_97",
    "emoji": "\ud83d\udc0d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 46,
    "attack": 26,
    "defense": 14,
    "speed": 26,
    "level": 1,
    "fun": "Dino_97 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_98",
    "emoji": "\ud83d\udc2d",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 47,
    "attack": 27,
    "defense": 15,
    "speed": 27,
    "level": 1,
    "fun": "Dino_98 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_99",
    "emoji": "\ud83e\udeb6",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 48,
    "attack": 28,
    "defense": 16,
    "speed": 28,
    "level": 1,
    "fun": "Dino_99 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_100",
    "emoji": "\ud83c\udfad",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 49,
    "attack": 29,
    "defense": 17,
    "speed": 29,
    "level": 1,
    "fun": "Dino_100 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_101",
    "emoji": "\ud83c\udf3f",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Rare",
    "hp": 50,
    "attack": 10,
    "defense": 18,
    "speed": 10,
    "level": 1,
    "fun": "Dino_101 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_102",
    "emoji": "\ud83d\udc26",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Legendary",
    "hp": 51,
    "attack": 11,
    "defense": 19,
    "speed": 11,
    "level": 1,
    "fun": "Dino_102 stomps wildly in the ancient world!"
  },
  {
    "name": "Dino_103",
    "emoji": "\ud83e\udd96",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Triceratopsdinosaur.png",
    "rarity": "Common",
    "hp": 52,
    "attack": 12,
    "defense": 20,
    "speed": 12,
    "level": 1,
    "fun": "Dino_103 stomps wildly in the ancient world!"
  }
]
